### ISSUE TITLE
Add Habitica to-dos to Google tasks and subtasks

### ISSUE THREAD

**Issue by miguelppais** [GimmikMe/Sync-Habitica-Todo-Google-Task#2]
If someone wants to use Habitica for task creation, but then use Google tasks integration with google calendar to organise a schedule and keep track of time.

- Import all Habitica due to-dos to google tasks, IF they are not listed already.
- To be run on a schedule (daily, after cron? Or maybe hourly because of the other features, BUT then it needs to avoid duplicate task import)

**Comment by miguelppais** [comment]
Base functionality already implemented by @GimmikMe

**Comment by miguelppais** [comment]
Maybe consider importing to a new GTasks tasklist called "Habitica"?

**Comment by GimmikMe** [comment]
Writing the ids of habitica tasks into the google task note and vise versa could be used to check if the task already exists in the corresponding tasklist.

Pros and cons I can think of:
+ relativly easy to implement
+ meets requirement of reducing API calls
- tasks take away more space on mobile (more notes)
- could confuse people
